[project]
name = "jaffle-bq-lightdash"
version = "0.1.0"
description = "dbt on BigQuery + Lightdash"
requires-python = ">=3.12"

dependencies = [
  "dbt-bigquery==1.8.*",
  "pandas>=2.2.0",
  "pyarrow>=16.0.0"
]

[tool.uv]
